# .github/workflows/release.yml

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup (Install node & pnpm)
        uses: ./.github/actions/setup

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Packages & Publish to npm
        run: pnpm build && pnpm pub:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
